import { Timestamp } from 'rxjs';

export class Tarjeta{
    codent:string;              
    codmar:number;              
    indtipt:number;             
    binenttip:string;           
    binproc:string;             
    numulttar:number;           
    inddebcre:number;           
    indbinemp:string;           
    rangosup:string;            
    rangoinf:string;            
    rutinapan:string;           
    codserv:number;             
    gencarpin:string;           
    indintpan:string;           
    indcmbpan:string;           
    indcmbpin:string;           
    nummesproren:number;        
    nummintar:number;           
    nummaxdia:number;           
    tecnologia:string;          
    indgenvisaphone:string;     
    indacttar:number;           
    fecalta:string;             
    fecini:string;              
    fecfin:string;              
    gruafin:string;             
    porcesafin:number;          
    porbontitafin:number;       
    indadmpres:string;          
    indpinpres:string;          
    vigtarpre :number;          
    indmesvigmin:number;        
    codclave:string;            
    indrescli:string;           
    fecexpmon:string;           
    exponente:number;           
    numkpin:number;             
    pista1:string;              
    pista2:string;              
    tamcodbarr:number;          
    forestamp:string;          
    indtarvir:string;           
    indoffpvv:string;           
    codentumo:string;           
    codofiumo:string;           
    usuarioumo:string;          
    codtermumo:string;          
    contcur:string;             

}